### ISSUE TITLE
Getting the error - Missing helper Get

### ISSUE THREAD

**Issue by somenathghosh** [godofredoninja/Mapache#23]
ERROR: [index.hbs] Missing helper: "get" 
 Rendering Error Page 
 Ghost caught a processing error in the middleware layer. 
 Error: [index.hbs] Missing helper: "get"

` at Object.<anonymous> (/srv/www/moments-of-lives/node_modules/express-hbs/node_modules/handlebars/dist/cjs/handlebars/base.js:86:13)
    at Object.eval (eval at createFunctionContext (/srv/www/moments-of-lives/node_modules/express-hbs/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:221:23), <anonymous>:6:68)
    at ret (/srv/www/moments-of-lives/node_modules/express-hbs/node_modules/handlebars/dist/cjs/handlebars/runtime.js:159:30)
    at ret (/srv/www/moments-of-lives/node_modules/express-hbs/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:488:21)
    at Object.invokePartial (/srv/www/moments-of-lives/node_modules/express-hbs/node_modules/handlebars/dist/cjs/handlebars/runtime.js:218:12)
    at Object.invokePartialWrapper [as invokePartial] (/srv/www/moments-of-lives/node_modules/express-hbs/node_modules/handlebars/dist/cjs/handlebars/runtime.js:61:39)
    at Object.eval (eval at createFunctionContext (/srv/www/moments-of-lives/node_modules/express-hbs/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:221:23), <anonymous>:12:23)
    at ret (/srv/www/moments-of-lives/node_modules/express-hbs/node_modules/handlebars/dist/cjs/handlebars/runtime.js:159:30)
    at ret (/srv/www/moments-of-lives/node_modules/express-hbs/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:488:21)
    at Object.invokePartial (/srv/www/moments-of-lives/node_modules/express-hbs/node_modules/handlebars/dist/cjs/handlebars/runtime.js:218:12)
    at Object.invokePartialWrapper [as invokePartial] (/srv/www/moments-of-lives/node_modules/express-hbs/node_modules/handlebars/dist/cjs/handlebars/runtime.js:61:39)
    at Object.eval (eval at createFunctionContext (/srv/www/moments-of-lives/node_modules/express-hbs/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:221:23), <anonymous>:6:23)
    at ret (/srv/www/moments-of-lives/node_modules/express-hbs/node_modules/handlebars/dist/cjs/handlebars/runtime.js:159:30)
    at ret (/srv/www/moments-of-lives/node_modules/express-hbs/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:488:21)
    at renderTemplate (/srv/www/moments-of-lives/node_modules/express-hbs/lib/hbs.js:481:13)
    at render (/srv/www/moments-of-lives/node_modules/express-hbs/lib/hbs.js:529:5)
    at renderIt (/srv/www/moments-of-lives/node_modules/express-hbs/lib/hbs.js:591:18)
    at /srv/www/moments-of-lives/node_modules/express-hbs/lib/hbs.js:601:11
    at _returnLayouts (/srv/www/moments-of-lives/node_modules/express-hbs/lib/hbs.js:138:7)
    at /srv/www/moments-of-lives/node_modules/express-hbs/lib/hbs.js:149:7
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12) `

Please help.

**Comment by somenathghosh** [comment]
Found it was old version of ghost. Thanks.

**Comment by jarvan4dev** [comment]
how do you solve it on the latest version? 0.7
